=== RLJO/odoo-academy/__discard__/academy_online_assets/static/mapxml/v1/notebook.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <xs:element name="name" type="xs:string"/>
  <xs:element name="description" type="xs:string"/>
  <xs:element name="author" type="xs:string"/>
  <xs:element name="preview" type="xs:string"/>
  <xs:element name="ornament" type="xs:string"/>
  
  <xs:element name="default">
    <xs:simpleType>
      <xs:restriction base="xs:NCName">
        <xs:enumeration value="Verdadero"/>
        <xs:enumeration value="Falso"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  
  <xs:element name="notebook">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element ref="description"/>
        <xs:element ref="author"/>
        <xs:element maxOccurs="unbounded" ref="activity"/>
      </xs:sequence>
      <xs:attribute name="stabilisers" type="xs:boolean"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="activity">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"/>
        <xs:element maxOccurs="unbounded" ref="block"/>
        <xs:element minOccurs="0" ref="preview"></xs:element>
        <xs:element minOccurs="0" ref="ornament"></xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="block">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0"  ref="name"/>
        <xs:sequence minOccurs="0">
          <xs:element ref="description"/>
          <xs:element ref="author"/>
        </xs:sequence>
        <xs:element maxOccurs="unbounded" ref="division"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="division">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="name"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="target"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="statement"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="statement">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="name"/>
          <xs:element ref="value"/>
        </xs:choice>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="description"/>
        <xs:element ref="default"/>
      </xs:sequence>
      <xs:attribute name="class" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="target">
    <xs:complexType>
      <xs:sequence>
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="name"/>
          <xs:element ref="value"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="class" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="value">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="target"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="statement"/>
      </xs:sequence>
      <xs:attribute name="class" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== RLJO/odoo-academy/modules/academy_online_assets/static/mapxml/v1/TitTabLmnTblNp.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet class="text/xsl" href="http://localhost:8069/academy_online_assets/static/mapxml/v1/notebook.xsl"?>

<notebook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://localhost:8069/academy_online_assets/static/mapxml/v1/notebook.xsd">

    <name>MAP - Simulacro 03</name>
    <description>Simulacro de Examen para el segundo ejercicio de Auxiliar Administrativo para la
        Administración General del Estado</description>
    <author>Jorge Soto Garcia</author>

    <activity>
        <name>PRUEBA DE TRANSCRIPCIÓN</name>

        <block>

            <name>Mecanografía</name>
            <description>Copie el texto propuesto a continuación. Si en el texto a transcribir
                detectase faltas de ortografía o acentuación, DEBERÁ corregirlas. Respete la
                estructura de párrafos del texto original y no altere los signos de
                puntuación.</description>
            <author>Jorge Soto Garcia</author>

            <division>

                <target>
                    <value><![CDATA[
<p>Texto</p>]]></value>
                </target>

            </division>

        </block>

    </activity>

    <activity>
        <name>PRUEBA DE MAQUETACIÓN</name>

        <block>
            <name>Propiedades de página</name>
            <division>

            </division>
        </block>

        <block>
            <name>Título</name>
            
            <division>
                <target>
                    <name>Texto 1</name>
                    <value></value>
                </target>
                
            </division>
        </block>
        
        <block>
            <name>Lista tabulada</name>
            
            <division>

            </division>
            
            <division>
                <name>Párrafo</name>
                <target>
                    <name>Texto 2</name>
                    <value></value>
                </target>
            </division>
            
            <division>
                <name>Resto de párrafos</name>
                <target>
                    <name>Texto 3</name>
                    <value></value>
                </target>
            </division>
            
            
        </block>
        
        <block>
            <name>Lista ordenada</name>
            
            <division>
                
            </division>
            
            <division>
                <name>Párrafos Nivel 1</name>
                <target>
                    <name>Texto 4</name>
                    <value></value>
                </target>
            </division>
            
            <division>
                <name>Párrafos Nivel 2</name>
                <target>
                    <name>Texto 5</name>
                    <value></value>
                </target>
            </division>
            
            <division>
                <name>Párrafos Nivel 3</name>
                <target>
                    <name>Texto 6</name>
                    <value></value>
                </target>
            </division>
            
        </block>
        
        <block>
            <name>Tabla</name>
            
            <division>
                
            </division>
            
            <division>
                <name>Fila 1</name>
                
            </division>

            <division>
                <name>Resto de filas</name>
                
            </division>
        </block>
        
        
        <block>
            <name>Nota al pie</name>
            
            <division>
                <statement>
                    <value>
                        <statement>
                            <name>Insertar</name>
                            <value>Nota al pie en el texto...</value>
                            <default>Falso</default>
                        </statement>
                        <statement>
                            <name>Texto</name>
                            <value>XXX</value>
                            <default>Falso</default>
                        </statement>
                    </value>
                    <default>Falso</default>
                </statement>  
            </division>
            
        </block>
        
        <preview>Solución/DocWord.jpg</preview>
    </activity>
    
    <activity>
        <name>PRUEBA DE EXCEL</name>
        <block>
            <division>
                
            </division>
        </block>
    </activity>
    
</notebook>
